/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.CustomerModel;
import dao.CustomerDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.FlowLayout;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author User
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        displayCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    // Database connection details
    private final String url_db = "jdbc:mysql://localhost:3306/carrental_management_system_db";
    private final String username_db = "carrental";
    private final String password_db = "pih8888";

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Modern Header Components
        headerPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        
        // Modern Sidebar Components
        sidebarPanel = new javax.swing.JPanel();
        sidebarHeader = new javax.swing.JPanel();
        userInfoLabel = new javax.swing.JLabel();
        navButtonPanel = new javax.swing.JPanel();
        manageCarsBtn = new javax.swing.JButton();
        registerCustomerBtn = new javax.swing.JButton();
        rentCarBtn = new javax.swing.JButton();
        returnCarBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        
        // Modern Main Content Components
        mainContentPanel = new javax.swing.JPanel();
        contentHeader = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        
        // Customer Form Card
        formCard = new javax.swing.JPanel();
        formTitleLabel = new javax.swing.JLabel();
        formFieldsPanel = new javax.swing.JPanel();
        custIdLabel = new javax.swing.JLabel();
        custIdField = new javax.swing.JTextField();
        custNameLabel = new javax.swing.JLabel();
        custNameField = new javax.swing.JTextField();
        custAddrLabel = new javax.swing.JLabel();
        custAddrField = new javax.swing.JTextField();
        custPhoneLabel = new javax.swing.JLabel();
        custPhoneField = new javax.swing.JTextField();
        formButtonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        
        // Data Table Card
        tableCard = new javax.swing.JPanel();
        tableHeaderPanel = new javax.swing.JPanel();
        tableTitleLabel = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        customersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(248, 250, 252));
        setUndecorated(true);
        setSize(1300, 700);
        setLocationRelativeTo(null);
        getContentPane().setLayout(new BorderLayout());

        // Modern Header Panel
        headerPanel.setBackground(new Color(15, 23, 42));
        headerPanel.setLayout(new BorderLayout());
        headerPanel.setPreferredSize(new Dimension(1300, 80));
        
        // Title and Subtitle
        javax.swing.JPanel titlePanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        titlePanel.setBackground(new Color(15, 23, 42));
        titlePanel.setOpaque(true);
        
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 28));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setText("BMW Car Rental Management");
        titlePanel.add(titleLabel);
        
        subtitleLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        subtitleLabel.setForeground(new Color(203, 213, 225));
        subtitleLabel.setText("The Ultimate Driving Machine");
        titlePanel.add(subtitleLabel);
        
        // Control buttons panel
        javax.swing.JPanel controlPanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.RIGHT));
        controlPanel.setBackground(new Color(15, 23, 42));
        controlPanel.setOpaque(true);
        
        closeBtn.setBackground(new Color(239, 68, 68));
        closeBtn.setForeground(Color.WHITE);
        closeBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        closeBtn.setText("✕");
        closeBtn.setBorderPainted(false);
        closeBtn.setFocusPainted(false);
        closeBtn.setPreferredSize(new Dimension(30, 30));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        controlPanel.add(closeBtn);
        
        minimizeBtn.setBackground(new Color(59, 130, 246));
        minimizeBtn.setForeground(Color.WHITE);
        minimizeBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        minimizeBtn.setText("−");
        minimizeBtn.setBorderPainted(false);
        minimizeBtn.setFocusPainted(false);
        minimizeBtn.setPreferredSize(new Dimension(30, 30));
        controlPanel.add(minimizeBtn);
        
        headerPanel.add(titlePanel, BorderLayout.WEST);
        headerPanel.add(controlPanel, BorderLayout.EAST);
        
        getContentPane().add(headerPanel, BorderLayout.NORTH);

        // Modern Sidebar Panel
        sidebarPanel.setBackground(new Color(30, 41, 59));
        sidebarPanel.setLayout(new BorderLayout());
        sidebarPanel.setPreferredSize(new Dimension(250, 0));
        
        // Sidebar Header
        sidebarHeader.setBackground(new Color(15, 23, 42));
        sidebarHeader.setLayout(new FlowLayout(FlowLayout.LEFT));
        sidebarHeader.setPreferredSize(new Dimension(250, 80));
        
        userInfoLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        userInfoLabel.setForeground(Color.WHITE);
        userInfoLabel.setText("Admin Dashboard");
        sidebarHeader.add(userInfoLabel);
        
        sidebarPanel.add(sidebarHeader, BorderLayout.NORTH);
        
        // Navigation Buttons Panel
        navButtonPanel.setBackground(new Color(30, 41, 59));
        navButtonPanel.setLayout(new GridLayout(5, 1, 10, 10));
        navButtonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // Navigation Buttons with modern styling
        manageCarsBtn.setBackground(new Color(59, 130, 246));
        manageCarsBtn.setForeground(Color.WHITE);
        manageCarsBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        manageCarsBtn.setText("🚗 Manage Cars");
        manageCarsBtn.setBorderPainted(false);
        manageCarsBtn.setFocusPainted(false);
        manageCarsBtn.setPreferredSize(new Dimension(200, 45));
        manageCarsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCarsBtnActionPerformed(evt);
            }
        });
        navButtonPanel.add(manageCarsBtn);
        
        registerCustomerBtn.setBackground(new Color(16, 185, 129));
        registerCustomerBtn.setForeground(Color.WHITE);
        registerCustomerBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        registerCustomerBtn.setText("👤 Register Customer");
        registerCustomerBtn.setBorderPainted(false);
        registerCustomerBtn.setFocusPainted(false);
        registerCustomerBtn.setPreferredSize(new Dimension(200, 45));
        registerCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCustomerBtnActionPerformed(evt);
            }
        });
        navButtonPanel.add(registerCustomerBtn);
        
        rentCarBtn.setBackground(new Color(245, 158, 11));
        rentCarBtn.setForeground(Color.WHITE);
        rentCarBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        rentCarBtn.setText("🔑 Rent Car");
        rentCarBtn.setBorderPainted(false);
        rentCarBtn.setFocusPainted(false);
        rentCarBtn.setPreferredSize(new Dimension(200, 45));
        rentCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarBtnActionPerformed(evt);
            }
        });
        navButtonPanel.add(rentCarBtn);
        
        returnCarBtn.setBackground(new Color(139, 92, 246));
        returnCarBtn.setForeground(Color.WHITE);
        returnCarBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        returnCarBtn.setText("🔙 Return Car");
        returnCarBtn.setBorderPainted(false);
        returnCarBtn.setFocusPainted(false);
        returnCarBtn.setPreferredSize(new Dimension(200, 45));
        returnCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarBtnActionPerformed(evt);
            }
        });
        navButtonPanel.add(returnCarBtn);
        
        logoutBtn.setBackground(new Color(239, 68, 68));
        logoutBtn.setForeground(Color.WHITE);
        logoutBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        logoutBtn.setText("🚪 Logout");
        logoutBtn.setBorderPainted(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new Dimension(200, 45));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        navButtonPanel.add(logoutBtn);
        
        sidebarPanel.add(navButtonPanel, BorderLayout.CENTER);
        
        getContentPane().add(sidebarPanel, BorderLayout.WEST);

        // Modern Main Content Panel
        mainContentPanel.setBackground(new Color(248, 250, 252));
        mainContentPanel.setLayout(new BorderLayout());
        
        // Content Header
        contentHeader.setBackground(Color.WHITE);
        contentHeader.setLayout(new BorderLayout());
        contentHeader.setPreferredSize(new Dimension(0, 80));
        contentHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        pageTitleLabel.setFont(new Font("Segoe UI", Font.BOLD, 24));
        pageTitleLabel.setForeground(new Color(15, 23, 42));
        pageTitleLabel.setText("Customer Management");
        contentHeader.add(pageTitleLabel, BorderLayout.WEST);
        
        // Search Panel
        searchPanel.setBackground(Color.WHITE);
        searchPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        
        searchField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        searchField.setForeground(new Color(51, 65, 85));
        searchField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
        ));
        searchField.setPreferredSize(new Dimension(300, 40));
        searchPanel.add(searchField);
        
        searchBtn.setBackground(new Color(59, 130, 246));
        searchBtn.setForeground(Color.WHITE);
        searchBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        searchBtn.setText("🔍 Search");
        searchBtn.setBorderPainted(false);
        searchBtn.setFocusPainted(false);
        searchBtn.setPreferredSize(new Dimension(100, 40));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        searchPanel.add(searchBtn);
        
        contentHeader.add(searchPanel, BorderLayout.EAST);
        mainContentPanel.add(contentHeader, BorderLayout.NORTH);

        // Main content area with form and table
        javax.swing.JPanel contentArea = new javax.swing.JPanel(new BorderLayout(20, 20));
        contentArea.setBackground(new Color(248, 250, 252));
        contentArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Customer Form Card
        formCard.setBackground(Color.WHITE);
        formCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));
        formCard.setLayout(new BorderLayout());
        
        formTitleLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        formTitleLabel.setForeground(new Color(15, 23, 42));
        formTitleLabel.setText("Customer Information");
        formCard.add(formTitleLabel, BorderLayout.NORTH);
        
        // Form Fields Panel
        formFieldsPanel.setBackground(Color.WHITE);
        formFieldsPanel.setLayout(new GridLayout(2, 4, 20, 20));
        
        // Customer ID Field
        custIdLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        custIdLabel.setForeground(new Color(51, 65, 85));
        custIdLabel.setText("Customer ID");
        formFieldsPanel.add(custIdLabel);
        
        custIdField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        custIdField.setForeground(new Color(51, 65, 85));
        custIdField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        formFieldsPanel.add(custIdField);
        
        // Customer Name Field
        custNameLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        custNameLabel.setForeground(new Color(51, 65, 85));
        custNameLabel.setText("Customer Name");
        formFieldsPanel.add(custNameLabel);
        
        custNameField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        custNameField.setForeground(new Color(51, 65, 85));
        custNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        formFieldsPanel.add(custNameField);
        
        // Address Field
        custAddrLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        custAddrLabel.setForeground(new Color(51, 65, 85));
        custAddrLabel.setText("Address");
        formFieldsPanel.add(custAddrLabel);
        
        custAddrField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        custAddrField.setForeground(new Color(51, 65, 85));
        custAddrField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        formFieldsPanel.add(custAddrField);
        
        // Phone Field
        custPhoneLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        custPhoneLabel.setForeground(new Color(51, 65, 85));
        custPhoneLabel.setText("Phone Number");
        formFieldsPanel.add(custPhoneLabel);
        
        custPhoneField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        custPhoneField.setForeground(new Color(51, 65, 85));
        custPhoneField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        formFieldsPanel.add(custPhoneField);
        
        formCard.add(formFieldsPanel, BorderLayout.CENTER);
        
        // Form Buttons Panel
        formButtonsPanel.setBackground(Color.WHITE);
        formButtonsPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        
        saveBtn.setBackground(new Color(16, 185, 129));
        saveBtn.setForeground(Color.WHITE);
        saveBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        saveBtn.setText("💾 Save");
        saveBtn.setBorderPainted(false);
        saveBtn.setFocusPainted(false);
        saveBtn.setPreferredSize(new Dimension(100, 35));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        formButtonsPanel.add(saveBtn);
        
        updateBtn.setBackground(new Color(59, 130, 246));
        updateBtn.setForeground(Color.WHITE);
        updateBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        updateBtn.setText("✏️ Update");
        updateBtn.setBorderPainted(false);
        updateBtn.setFocusPainted(false);
        updateBtn.setPreferredSize(new Dimension(100, 35));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        formButtonsPanel.add(updateBtn);
        
        deleteBtn.setBackground(new Color(239, 68, 68));
        deleteBtn.setForeground(Color.WHITE);
        deleteBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        deleteBtn.setText("🗑️ Delete");
        deleteBtn.setBorderPainted(false);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setPreferredSize(new Dimension(100, 35));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        formButtonsPanel.add(deleteBtn);
        
        resetBtn.setBackground(new Color(107, 114, 128));
        resetBtn.setForeground(Color.WHITE);
        resetBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        resetBtn.setText("🔄 Reset");
        resetBtn.setBorderPainted(false);
        resetBtn.setFocusPainted(false);
        resetBtn.setPreferredSize(new Dimension(100, 35));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        formButtonsPanel.add(resetBtn);
        
        formCard.add(formButtonsPanel, BorderLayout.SOUTH);
        contentArea.add(formCard, BorderLayout.WEST);

        // Data Table Card
        tableCard.setBackground(Color.WHITE);
        tableCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));
        tableCard.setLayout(new BorderLayout());
        
        // Table Header Panel
        tableHeaderPanel.setBackground(Color.WHITE);
        tableHeaderPanel.setLayout(new BorderLayout());
        
        tableTitleLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        tableTitleLabel.setForeground(new Color(15, 23, 42));
        tableTitleLabel.setText("Customer Database");
        tableHeaderPanel.add(tableTitleLabel, BorderLayout.WEST);
        
        printBtn.setBackground(new Color(107, 114, 128));
        printBtn.setForeground(Color.WHITE);
        printBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        printBtn.setText("🖨️ Print");
        printBtn.setBorderPainted(false);
        printBtn.setFocusPainted(false);
        printBtn.setPreferredSize(new Dimension(80, 30));
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        tableHeaderPanel.add(printBtn, BorderLayout.EAST);
        
        tableCard.add(tableHeaderPanel, BorderLayout.NORTH);
        
        // Modern Table
        customersTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        customersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Phone"
            }
        ));
        customersTable.setRowHeight(35);
        customersTable.setSelectionBackground(new Color(59, 130, 246));
        customersTable.setSelectionForeground(Color.WHITE);
        customersTable.setGridColor(new Color(226, 232, 240));
        customersTable.setShowGrid(true);
        customersTable.setShowHorizontalLines(true);
        customersTable.setShowVerticalLines(false);
        customersTable.getTableHeader().setBackground(new Color(248, 250, 252));
        customersTable.getTableHeader().setForeground(new Color(51, 65, 85));
        customersTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        customersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersTableMouseClicked(evt);
            }
        });
        
        tableScrollPane.setViewportView(customersTable);
        tableScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240), 1));
        tableScrollPane.setBackground(Color.WHITE);
        
        tableCard.add(tableScrollPane, BorderLayout.CENTER);
        contentArea.add(tableCard, BorderLayout.CENTER);
        
        mainContentPanel.add(contentArea, BorderLayout.CENTER);
        getContentPane().add(mainContentPanel, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Modern Event Handlers
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    
    private void manageCarsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new ManageCars().setVisible(true);
        this.dispose();
    }
    
    private void registerCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new Customer().setVisible(true);
        this.dispose();
    }
    
    private void rentCarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new RentCar().setVisible(true);
        this.dispose();
    }
    
    private void returnCarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new ReturnCar().setVisible(true);
        this.dispose();
    }
    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new Login().setVisible(true);
        this.dispose();
    }
    
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {
        SearchCustomer();
    }
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        SaveCustomer();
    }
    
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {
        UpdateCustomer();
    }
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {
        DeleteCustomer();
    }
    
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {
        ResetForm();
    }
    
    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            customersTable.print(JTable.PrintMode.NORMAL, null, null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void customersTableMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel model = (DefaultTableModel) customersTable.getModel();
        int selectedRow = customersTable.getSelectedRow();
        if (selectedRow >= 0) {
            custIdField.setText(model.getValueAt(selectedRow, 0).toString());
            custNameField.setText(model.getValueAt(selectedRow, 1).toString());
            custAddrField.setText(model.getValueAt(selectedRow, 2).toString());
            custPhoneField.setText(model.getValueAt(selectedRow, 3).toString());
        }
    }

    // Modern Business Logic Methods
    private void SearchCustomer() {
        String keyword = searchField.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
            return;
        }
        try {
            ResultSet rs = new dao.CustomerDao().searchCustomer(keyword);
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                    new Object[]{"ID", "Name", "Address", "Phone"}, 0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getString("CUSTID"),
                        rs.getString("CUSTNAME"),
                        rs.getString("CUSTADDR"),
                        rs.getString("CUSTPHONE")  
                });
            }
            customersTable.setModel(model);
            rs.getStatement().getConnection().close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void SaveCustomer() {
        String custIdStr = custIdField.getText().trim();
        String custName = custNameField.getText().trim();
        String custAddr = custAddrField.getText().trim();
        String custPhone = custPhoneField.getText().trim();

        if (custIdStr.isEmpty() || custName.isEmpty() || custAddr.isEmpty() || custPhone.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all the customer information.");
        }
        else if (!custIdStr.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Customer ID must be a valid number.");
        }
        else if (!custPhone.matches("\\+250\\s\\d{3}\\s\\d{3}\\s\\d{3}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be in the format: +250 785 373 124.");
        }
        else {
            try {
                int custId = Integer.parseInt(custIdStr);
                CustomerModel customer = new CustomerModel(custId, custName, custAddr, custPhone);
                customerDAO.insertCustomer(customer);
                javax.swing.JOptionPane.showMessageDialog(this, "Customer Saved Successfully");
                displayCustomers();
                ResetForm();
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error Saving Customer. See console for details.");
            }
        }
    }
    
    private void UpdateCustomer() {
        String custIdStr = custIdField.getText().trim();
        String custName = custNameField.getText().trim();
        String custAddr = custAddrField.getText().trim();
        String custPhone = custPhoneField.getText().trim();

        if (custIdStr.isEmpty() || custName.isEmpty() || custAddr.isEmpty() || custPhone.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all the customer information to edit.");
        }
        else if (!custIdStr.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Customer ID must be a valid number.");
        }
        else if (!custPhone.matches("\\+250\\s\\d{3}\\s\\d{3}\\s\\d{3}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be in the format: +250 785 373 124.");
        }
        else {
            try {
                int custId = Integer.parseInt(custIdStr);
                CustomerModel customer = new CustomerModel(custId, custName, custAddr, custPhone);
                new dao.CustomerDao().updateCustomer(customer);
                javax.swing.JOptionPane.showMessageDialog(this, "Customer Updated Successfully");
                displayCustomers();
                ResetForm();
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error Updating Customer. See console for details.");
            }
        }
    }
    
    private void DeleteCustomer() {
        if (custIdField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input the Customer ID to delete a Customer");
        } else {
            int custId = Integer.parseInt(custIdField.getText());
            customerDAO.deleteCustomer(custId);
            javax.swing.JOptionPane.showMessageDialog(this, "Customer Deleted Successfully");
            displayCustomers();
            ResetForm();
        }
    }
    
    private void ResetForm() {
        custIdField.setText("");
        custNameField.setText("");
        custAddrField.setText("");
        custPhoneField.setText("");
    }
    
    private void displayCustomers() {
        customerDAO.getAllCustomers(customersTable);
    }

    // Variables declaration - Modern Components
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel subtitleLabel;
    
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel sidebarHeader;
    private javax.swing.JLabel userInfoLabel;
    private javax.swing.JPanel navButtonPanel;
    private javax.swing.JButton manageCarsBtn;
    private javax.swing.JButton registerCustomerBtn;
    private javax.swing.JButton rentCarBtn;
    private javax.swing.JButton returnCarBtn;
    private javax.swing.JButton logoutBtn;
    
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel contentHeader;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchBtn;
    
    private javax.swing.JPanel formCard;
    private javax.swing.JLabel formTitleLabel;
    private javax.swing.JPanel formFieldsPanel;
    private javax.swing.JLabel custIdLabel;
    private javax.swing.JTextField custIdField;
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JTextField custNameField;
    private javax.swing.JLabel custAddrLabel;
    private javax.swing.JTextField custAddrField;
    private javax.swing.JLabel custPhoneLabel;
    private javax.swing.JTextField custPhoneField;
    private javax.swing.JPanel formButtonsPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton resetBtn;
    
    private javax.swing.JPanel tableCard;
    private javax.swing.JPanel tableHeaderPanel;
    private javax.swing.JLabel tableTitleLabel;
    private javax.swing.JButton printBtn;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable customersTable;
    
    CustomerDao customerDAO = new CustomerDao();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }
}