/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RentCar extends javax.swing.JFrame {

    /**
     * Creates new form CarServices
     */
    public RentCar() {
        initComponents();
        DisplayCars();
        DisplayRentCars();
        GetCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    // Database connection details
    private final String url_db = "jdbc:mysql://localhost:3306/carrental_management_system_db";
    private final String username_db = "carrental";
    private final String password_db = "pih8888";

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseClick = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ManageCarBtn = new usu.widget.ButtonGlass();
        RegisterCustomerBtn = new usu.widget.ButtonGlass();
        RentCarBtn = new usu.widget.ButtonGlass();
        ReturnCarBtn = new usu.widget.ButtonGlass();
        LogOutBtn = new usu.widget.ButtonGlass();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PlateNumTb = new javax.swing.JTextField();
        RentIdTb = new javax.swing.JTextField();
        FeesTb = new javax.swing.JTextField();
        ModelTb = new javax.swing.JTextField();
        CustNameCb = new javax.swing.JComboBox<String>();
        ResetBtn = new javax.swing.JButton();
        PrintBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarsTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        ReturnDate = new com.toedter.calendar.JDateChooser();
        RentDate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RentTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        SaveBtn1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        SearchTb = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseClick.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        CloseClick.setForeground(new java.awt.Color(0, 0, 102));
        CloseClick.setText("x");
        CloseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseClickMouseClicked(evt);
            }
        });
        getContentPane().add(CloseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("BMW Car Rental Software");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 490, -1));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("BMW-Bayerische Motoren Werke");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 230, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 20, 80));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("/");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 80));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("/");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageCarBtn.setText("Manage Cars");
        ManageCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        ManageCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCarBtnMouseClicked(evt);
            }
        });
        ManageCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ManageCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 30));

        RegisterCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterCustomerBtn.setText("Register Customer");
        RegisterCustomerBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        RegisterCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterCustomerBtnMouseClicked(evt);
            }
        });
        RegisterCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        RentCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        RentCarBtn.setText("Rent Car");
        RentCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        RentCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentCarBtnMouseClicked(evt);
            }
        });
        RentCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RentCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 30));

        ReturnCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReturnCarBtn.setText("Return Car");
        ReturnCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        ReturnCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnCarBtnMouseClicked(evt);
            }
        });
        ReturnCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ReturnCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 30));

        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Logout");
        LogOutBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseClicked(evt);
            }
        });
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 610));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("AVAILABLE CARS FOR RENT");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Rent ID");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 71, -1, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Plate Number");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 20));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Model");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Customer Name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Return Date");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 80, -1));

        PlateNumTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        PlateNumTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(PlateNumTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 32));

        RentIdTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        RentIdTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(RentIdTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 32));

        FeesTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        FeesTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(FeesTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 90, 32));

        ModelTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ModelTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(ModelTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 130, 32));

        CustNameCb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        CustNameCb.setForeground(new java.awt.Color(0, 0, 102));
        CustNameCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNameCbActionPerformed(evt);
            }
        });
        jPanel5.add(CustNameCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 170, 30));

        ResetBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(0, 0, 102));
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 110, 30));

        PrintBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PrintBtn.setForeground(new java.awt.Color(0, 0, 102));
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        jPanel5.add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 110, -1));

        EditBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(0, 0, 102));
        EditBtn.setText("Update Rental");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel5.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 130, 30));

        DeleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(0, 0, 102));
        DeleteBtn.setText("Delete Rental");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel5.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 160, -1, 30));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("RENT A CAR");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        CarsTable.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        CarsTable.setForeground(new java.awt.Color(0, 0, 102));
        CarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "PLATENUM", "TYPE", "MODEL", "PRICE", "STATUS"
            }
        ));
        CarsTable.setRowHeight(25);
        CarsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarsTable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 790, 130));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Rent Fee");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, -1, -1));

        ReturnDate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jPanel5.add(ReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 160, 30));

        RentDate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jPanel5.add(RentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 170, 30));

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Rent Date");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        RentTable.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        RentTable.setForeground(new java.awt.Color(0, 0, 102));
        RentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RENTID", "PLATENUM", "MODEL", "CUSTOMER", "RENTDATE", "RETURNDATE", "FEES"
            }
        ));
        RentTable.setRowHeight(25);
        RentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(RentTable);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 790, 140));

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("CARS CURRENTLY ON RENT");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, 50));

        SaveBtn1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SaveBtn1.setForeground(new java.awt.Color(0, 0, 102));
        SaveBtn1.setText("Register Rental");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 160, -1, 30));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Search:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        SearchTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        SearchTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(SearchTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 180, 30));

        SearchBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 0, 102));
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        jPanel5.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 100, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 1060, 600));

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("The Ultimate Driving Machine");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 230, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseClickMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseClickMouseClicked

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
        try {
            RentTable.print(JTable.PrintMode.NORMAL, null, null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void ManageCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCarBtnMouseClicked
        // TODO add your handling code here:
        new ManageCars().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageCarBtnMouseClicked

    private void ManageCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCarBtnActionPerformed

    private void RegisterCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCustomerBtnMouseClicked
        // TODO add your handling code here:
        new Customer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterCustomerBtnMouseClicked

    private void RegisterCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerBtnActionPerformed

    private void RentCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentCarBtnMouseClicked
        // TODO add your handling code here:
        new RentCar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RentCarBtnMouseClicked

    private void RentCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentCarBtnActionPerformed

    private void ReturnCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnCarBtnMouseClicked
        // TODO add your handling code here:
        new ReturnCar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnCarBtnMouseClicked

    private void ReturnCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnCarBtnActionPerformed

    private void LogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnMouseClicked

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        // TODO add your handling code here:
        SearchCars();
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void SearchCars() {
    String keyword = SearchTb.getText().trim();
    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
        return;
    }
    try {
        ResultSet rs = new dao.ManageCarsDao().searchCars(keyword);
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[]{"PLATENUM", "TYPE", "MODEL", "PRICE", "STATUS"}, 0);

        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getString("PLATENUM"),
                    rs.getString("TYPE"),
                    rs.getString("MODEL"),
                    rs.getString("PRICE"),
                    rs.getString("STATUS")
            });
        }
        CarsTable.setModel(model);
        rs.getStatement().getConnection().close();
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void CustNameCbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CustNameCbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_CustNameCbActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        Reset();
    }// GEN-LAST:event_ResetBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        if (PlateNumTb.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "Input the Plate Number to delete a Rented Car");

        } else {

            try {
                Con = DriverManager.getConnection(url_db, username_db, password_db);
                String Plate = PlateNumTb.getText();
                // Prepare the SQL statement to delete the car
                String query = "DELETE FROM renttable WHERE PLATENUM=?";
                // Use PreparedStatement to prevent SQL injection
                PreparedStatement pst = Con.prepareStatement(query);
                pst.setString(1, Plate);
                int row = pst.executeUpdate();
                if (row > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Rent Car Deleted Successfully");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error Deleting Rent Car");
                }
                Con.close();
                // Clear the input fields after deleting
                RentIdTb.setText("");
                PlateNumTb.setText("");
                ModelTb.setText("");
                FeesTb.setText("");
                RentDate.setDate(null);
                ReturnDate.setDate(null);
                CustNameCb.setSelectedIndex(-1);
                // Refresh the table data
                DisplayCars();
                DisplayRentCars();
                // Reset
                Reset();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_DeleteBtnActionPerformed

    private void Reset() {
        RentIdTb.setText("");
        PlateNumTb.setText("");
        ModelTb.setText("");
        FeesTb.setText("");
        RentDate.setDate(null);
        ReturnDate.setDate(null);
        CustNameCb.setSelectedIndex(-1);
    }

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        if (RentIdTb.getText().isEmpty() || PlateNumTb.getText().isEmpty() || ModelTb.getText().isEmpty() ||
                FeesTb.getText().isEmpty() || CustNameCb.getSelectedItem().toString().isEmpty() ||
                RentDate.getDate() == null || ReturnDate.getDate() == null) {

            javax.swing.JOptionPane.showMessageDialog(this, "Input the Data of the Rented BMW to be Edited");

        } else {

            DateRent = new java.util.Date();
            DateRent = RentDate.getDate();
            RentDat = new java.sql.Date(DateRent.getTime());
            DateReturn = new java.util.Date();
            DateReturn = ReturnDate.getDate();
            returnDateSql = new java.sql.Date(DateReturn.getTime());

            try {
                // Establish the database connection
                Con = DriverManager.getConnection(url_db, username_db, password_db);
                int RId = Integer.parseInt(RentIdTb.getText());
                // Prepare the SQL statement to update the car
                String query = "UPDATE renttable SET PLATENUM=?, MODEL=?, CUSTNAME=?, RENTDATE=?, RETURNDATE=?, RENTFEE=? WHERE RENTID=?";
                // Use PreparedStatement to prevent SQL injection
                PreparedStatement pst = Con.prepareStatement(query);
                pst.setString(1, PlateNumTb.getText());
                pst.setString(2, ModelTb.getText());
                pst.setString(3, CustNameCb.getSelectedItem().toString());
                pst.setDate(4, RentDat);
                pst.setDate(5, returnDateSql);
                pst.setDouble(6, Double.parseDouble(FeesTb.getText()));
                pst.setInt(7, RId);
                // Set the parameters for the prepared statement
                // Execute the update
                int row = pst.executeUpdate();
                if (row > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Rent Car Updated Successfully");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error Updating Rent Car");
                }
                Con.close();
                // Clear the input fields after updating

                // Refresh the table data
                DisplayCars();
                DisplayRentCars();
                Reset();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_EditBtnActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void RentTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RentTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) RentTable.getModel();
        int MyIndex = RentTable.getSelectedRow();
        RentIdTb.setText(model.getValueAt(MyIndex, 0).toString());
        PlateNumTb.setText(model.getValueAt(MyIndex, 1).toString());
        ModelTb.setText(model.getValueAt(MyIndex, 2).toString());
        CustNameCb.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        RentDate.setDate((java.util.Date) model.getValueAt(MyIndex, 4));
        ReturnDate.setDate((java.util.Date) model.getValueAt(MyIndex, 5));
        FeesTb.setText(model.getValueAt(MyIndex, 6).toString());

    }// GEN-LAST:event_RentTableMouseClicked

    private void UpdateCar() {

        try {
            Con = DriverManager.getConnection(url_db, username_db, password_db);
            String Plate = PlateNumTb.getText();
            String CarStatus = "Booked";
            // Update the car status in the database
            String query = "UPDATE carstable SET STATUS=? WHERE PLATENUM=?";
            // Use PreparedStatement to prevent SQL injection
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, CarStatus);
            pst.setString(2, Plate);
            int row = pst.executeUpdate();
            if (row > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Car Has Been Booked Successfully, Its no longer available for Rent");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error While Booking Car");
            }
            Con.close();

            // Refresh the table data
            DisplayCars();
            Reset();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    java.util.Date DateRent, DateReturn;
    java.sql.Date RentDat, returnDateSql;

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
        if (PlateNumTb.getText().isEmpty() || ModelTb.getText().isEmpty() || FeesTb.getText().isEmpty() ||
                RentIdTb.getText().isEmpty() || CustNameCb.getSelectedItem().toString().isEmpty() ||
                RentDate.getDate() == null || ReturnDate.getDate() == null) {

            javax.swing.JOptionPane.showMessageDialog(this, "Input all necessary data, Rn some Data are missing");

        } else {

            DateRent = new java.util.Date();
            DateRent = RentDate.getDate();
            RentDat = new java.sql.Date(DateRent.getTime());
            DateReturn = new java.util.Date();
            DateReturn = ReturnDate.getDate();
            returnDateSql = new java.sql.Date(DateReturn.getTime());

            try {

                // Establish the database connection
                Con = DriverManager.getConnection(url_db, username_db, password_db);
                PreparedStatement pst = Con.prepareStatement("insert into renttable values(?,?,?,?,?,?,?)");
                pst.setString(1, RentIdTb.getText());
                pst.setString(2, PlateNumTb.getText());
                pst.setString(3, ModelTb.getText());
                pst.setString(4, CustNameCb.getSelectedItem().toString());
                pst.setDate(5, RentDat);
                pst.setDate(6, returnDateSql);
                pst.setString(7, FeesTb.getText());
                int row = pst.executeUpdate();
                if (row > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Rent Car Added Successfully");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error Adding Rent Car");
                }
                Con.close();

                // Refresh the table data
                DisplayRentCars();
                DisplayCars();
                // Update the car status
                UpdateCar();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_SaveBtn1ActionPerformed

    private void DisplayRentCars() {
        // Implement the method to load Rent cars from the database and display them in
        // renttable
        try {
            Con = DriverManager.getConnection(url_db, username_db, password_db);
            St = Con.createStatement();
            Rs = St.executeQuery("select * from renttable");
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                    new Object[] { "RENTID", "PLATENUM", "MODEL", "CUSTNAME", "RENTDATE", "RETURNDATE", "RENTFEE" }, 0);
            while (Rs.next()) {
                model.addRow(new Object[] {
                        Rs.getString("RENTID"),
                        Rs.getString("PLATENUM"),
                        Rs.getString("MODEL"),
                        Rs.getString("CUSTNAME"),
                        Rs.getDate("RENTDATE"),
                        Rs.getDate("RETURNDATE"),
                        Rs.getString("RENTFEE")
                });
            }
            RentTable.setModel(model);
        } catch (Exception e) {
        }
    }

    private void CarsTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_CarsTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) CarsTable.getModel();
        int MyIndex = CarsTable.getSelectedRow();
        PlateNumTb.setText(model.getValueAt(MyIndex, 0).toString());
        ModelTb.setText(model.getValueAt(MyIndex, 2).toString());
        FeesTb.setText(model.getValueAt(MyIndex, 3).toString());

    }// GEN-LAST:event_CarsTableMouseClicked

    /**
     * @param args the command line arguments
     */

    private void DisplayCars() {
        // Implement the method to load cars from the database and display them in
        // CarsTable
        try (Connection con = DriverManager.getConnection(url_db, username_db, password_db);
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from carstable where status='Available'")) {

            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                    new Object[] { "PLATENUM", "TYPE", "MODEL", "PRICE", "STATUS" }, 0);
            while (rs.next()) {
                model.addRow(new Object[] {
                        rs.getString("PLATENUM"),
                        rs.getString("TYPE"),
                        rs.getString("MODEL"),
                        rs.getString("PRICE"),
                        rs.getString("STATUS")
                });
            }
            CarsTable.setModel(model);
        } catch (java.sql.SQLException e) {
            e.printStackTrace(); // Log the SQL exception
        } catch (Exception e) {
            e.printStackTrace(); // Log any other exceptions
        }
    }

    public void GetCustomers() {
        try {
            Connection con = DriverManager.getConnection(url_db, username_db, password_db);
            Statement st = con.createStatement();
            String query = "select * from customerstable";
            ResultSet rs = st.executeQuery("select * from customerstable");
            while (rs.next()) {
                String customer = rs.getString("CustName");
                CustNameCb.addItem(customer);
            }
        } catch (Exception e) {
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarsTable;
    private javax.swing.JLabel CloseClick;
    private javax.swing.JComboBox<String> CustNameCb;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField FeesTb;
    private usu.widget.ButtonGlass LogOutBtn;
    private usu.widget.ButtonGlass ManageCarBtn;
    private javax.swing.JTextField ModelTb;
    private javax.swing.JTextField PlateNumTb;
    private javax.swing.JButton PrintBtn;
    private usu.widget.ButtonGlass RegisterCustomerBtn;
    private usu.widget.ButtonGlass RentCarBtn;
    private com.toedter.calendar.JDateChooser RentDate;
    private javax.swing.JTextField RentIdTb;
    private javax.swing.JTable RentTable;
    private javax.swing.JButton ResetBtn;
    private usu.widget.ButtonGlass ReturnCarBtn;
    private com.toedter.calendar.JDateChooser ReturnDate;
    private javax.swing.JButton SaveBtn1;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
