/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ReturnDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ReturnModel;

/**
 *
 * @author User
 */
public class ReturnCar extends javax.swing.JFrame {

    /**
     * Creates new form CarServices
     */
    public ReturnCar() {
        initComponents();

        DisplayRentCars();
        DisplayReturnCars();
        GetCustomers();
        RemoveFromRentCars();
        CustNameCb.setEditable(false);
        PlateNumTb1.setEditable(false);
        ModelTb.setEditable(false);
        FineTB.setEditable(false);
    }

    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    // Database connection details
    private final String url_db = "jdbc:mysql://localhost:3306/carrental_management_system_db";
    private final String username_db = "carrental";
    private final String password_db = "pih8888";
    
    ReturnDao returnDao = new ReturnDao();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseClick = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ManageCarBtn = new usu.widget.ButtonGlass();
        RegisterCustomerBtn = new usu.widget.ButtonGlass();
        RentCarBtn = new usu.widget.ButtonGlass();
        ReturnCarBtn = new usu.widget.ButtonGlass();
        LogOutBtn = new usu.widget.ButtonGlass();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FineTB = new javax.swing.JTextField();
        ReturnIdTb = new javax.swing.JTextField();
        ReturnBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReturnTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RentTable = new javax.swing.JTable();
        ReturnDate = new com.toedter.calendar.JDateChooser();
        Generatelbl = new javax.swing.JLabel();
        DelayTb = new javax.swing.JTextField();
        PrintBtn = new javax.swing.JButton();
        CustNameCb = new javax.swing.JComboBox<String>();
        jLabel22 = new javax.swing.JLabel();
        PlateNumTb1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ModelTb = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        SearchTb = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseClick.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        CloseClick.setForeground(new java.awt.Color(0, 0, 102));
        CloseClick.setText("x");
        CloseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseClickMouseClicked(evt);
            }
        });
        getContentPane().add(CloseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("BMW Car Rental Software");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 460, -1));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("BMW-Bayerische Motoren Werke");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 230, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 20, 80));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("/");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 80));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("/");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageCarBtn.setText("Manage Cars");
        ManageCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        ManageCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCarBtnMouseClicked(evt);
            }
        });
        ManageCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ManageCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 30));

        RegisterCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterCustomerBtn.setText("Register Customer");
        RegisterCustomerBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        RegisterCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterCustomerBtnMouseClicked(evt);
            }
        });
        RegisterCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        RentCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        RentCarBtn.setText("Rent Car");
        RentCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        RentCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentCarBtnMouseClicked(evt);
            }
        });
        RentCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RentCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 30));

        ReturnCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReturnCarBtn.setText("Return Car");
        ReturnCarBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        ReturnCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnCarBtnMouseClicked(evt);
            }
        });
        ReturnCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ReturnCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 30));

        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Logout");
        LogOutBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseClicked(evt);
            }
        });
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 610));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Cars Currently On Rent");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Return ID");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Model");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Return Date");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Fine");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        FineTB.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        FineTB.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(FineTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 149, 32));

        ReturnIdTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ReturnIdTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(ReturnIdTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 149, 32));

        ReturnBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ReturnBtn.setForeground(new java.awt.Color(0, 0, 102));
        ReturnBtn.setText("Return");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ReturnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 110, 30));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("RETURN CAR");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 40));

        ReturnTable.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        ReturnTable.setForeground(new java.awt.Color(0, 0, 102));
        ReturnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RETURNID", "PLATENUM", "MODEL", "CUSTNAME", "RETURNDATE", "MODEL", "FINE"
            }
        ));
        ReturnTable.setRowHeight(25);
        jScrollPane1.setViewportView(ReturnTable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 790, 160));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Customer Name");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Cars Returned");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, 30));

        RentTable.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        RentTable.setForeground(new java.awt.Color(0, 0, 102));
        RentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RENTID", "PLATENUM", "MODEL", "CUSTOMER", "RENTDATE", "RETURNDATE", "FEES"
            }
        ));
        RentTable.setRowHeight(25);
        RentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(RentTable);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 790, 170));

        ReturnDate.setForeground(new java.awt.Color(0, 0, 102));
        ReturnDate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jPanel5.add(ReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 30));

        Generatelbl.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Generatelbl.setForeground(new java.awt.Color(0, 0, 102));
        Generatelbl.setText("Generate");
        Generatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneratelblMouseClicked(evt);
            }
        });
        jPanel5.add(Generatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        DelayTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        DelayTb.setForeground(new java.awt.Color(0, 0, 102));
        DelayTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelayTbActionPerformed(evt);
            }
        });
        jPanel5.add(DelayTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 149, 32));

        PrintBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PrintBtn.setForeground(new java.awt.Color(0, 0, 102));
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        jPanel5.add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 110, 30));

        CustNameCb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        CustNameCb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(CustNameCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 30));

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Plate Number");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        PlateNumTb1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        PlateNumTb1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(PlateNumTb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 149, 32));

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Delay");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        ModelTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ModelTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(ModelTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 149, 32));

        DeleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(0, 0, 102));
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel5.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 110, 30));

        SearchTb.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        SearchTb.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(SearchTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 160, 30));

        SearchBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 0, 102));
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        jPanel5.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 80, 30));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Search:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 34, 50, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 1060, 600));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("The Ultimate Driving Machine");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 200, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseClickMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseClickMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        
       if (PlateNumTb1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select The Car to be Deleted");
    } else {
        returnDao.deleteReturnCar(PlateNumTb1.getText());
        DisplayReturnCars();
    } 
        
        
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void ManageCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCarBtnMouseClicked
        // TODO add your handling code here:
        new ManageCars().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageCarBtnMouseClicked

    private void ManageCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCarBtnActionPerformed

    private void RegisterCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCustomerBtnMouseClicked
        // TODO add your handling code here:
        new Customer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterCustomerBtnMouseClicked

    private void RegisterCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerBtnActionPerformed

    private void RentCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentCarBtnMouseClicked
        // TODO add your handling code here:
        new RentCar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RentCarBtnMouseClicked

    private void RentCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentCarBtnActionPerformed

    private void ReturnCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnCarBtnMouseClicked
        // TODO add your handling code here:
        new ReturnCar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnCarBtnMouseClicked

    private void ReturnCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnCarBtnActionPerformed

    private void LogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnMouseClicked

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        // TODO add your handling code here:
        SearchRent();
    }//GEN-LAST:event_SearchBtnMouseClicked

    
   private void SearchRent() {
    String keyword = SearchTb.getText().trim();
    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
        return;
    }
    try {
        ResultSet rs = new dao.ReturnDao().searchRent(keyword);
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                    new Object[] { "RENTID", "PLATENUM", "MODEL", "CUSTNAME", "RENTDATE", "RETURNDATE", "RENTFEE" }, 0);
            while (Rs.next()) {
                model.addRow(new Object[] {
                        Rs.getString("RENTID"),
                        Rs.getString("PLATENUM"),
                        Rs.getString("MODEL"),
                        Rs.getString("CUSTNAME"),
                        Rs.getDate("RENTDATE"),
                        Rs.getDate("RETURNDATE"),
                        Rs.getString("RENTFEE")
                });
            }
            RentTable.setModel(model);
        } catch (Exception e) {
            
        }
   }

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
        try {
            ReturnTable.print(JTable.PrintMode.NORMAL, null, null);
        } catch (Exception e) {
        }
    }// GEN-LAST:event_PrintBtnActionPerformed

    int cost = 50;
    int Fine = 0;

    private void GeneratelblMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_GeneratelblMouseClicked

        if (cost == 0) {

            JOptionPane.showMessageDialog(this, "Please select the car to return");

        } else {
            int Fine = cost * Integer.parseInt(DelayTb.getText());
            FineTB.setText(String.valueOf(Fine));
            int total = cost + Fine;
        }

    }// GEN-LAST:event_GeneratelblMouseClicked

    java.util.Date DateRent, DateReturn;
    java.sql.Date RentDat = null;
    java.sql.Date returnDateSql = null;

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {
    if (ReturnIdTb.getText().isEmpty() || FineTB.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information");
    } else {
        ReturnModel returnCar = new ReturnModel(
            ReturnIdTb.getText(),
            PlateNumTb1.getText(),
            ModelTb.getText(),
            CustNameCb.getSelectedItem().toString(),
            java.sql.Date.valueOf(ReturnDate.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate()),
            DelayTb.getText(),
            FineTB.getText()
        );
        
        returnDao.insertReturnCar(returnCar);
        returnDao.deleteRentCar(PlateNumTb1.getText());
        returnDao.updateCarStatus(PlateNumTb1.getText());
        
        DisplayRentCars();
        DisplayReturnCars();
        }
    }// GEN-LAST:event_ReturnBtnActionPerformed

    private void RentTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RentTableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) RentTable.getModel();
        int MyIndex = RentTable.getSelectedRow();
        PlateNumTb1.setText(model.getValueAt(MyIndex, 1).toString());
        ModelTb.setText(model.getValueAt(MyIndex, 2).toString());
        CustNameCb.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        ReturnDate.setDate((java.util.Date) model.getValueAt(MyIndex, 4));

    }// GEN-LAST:event_RentTableMouseClicked

    private void DelayTbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DelayTbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_DelayTbActionPerformed

    private void DisplayRentCars() {
        returnDao.displayRentCars(RentTable);
    }


    private void DisplayReturnCars() {
        returnDao.displayReturnCars(ReturnTable);
    }


    private void RemoveFromRentCars() {
        // Implement the method to delete a rent car from the database
        try {
            Con = DriverManager.getConnection(url_db, username_db, password_db);
            String query = "DELETE FROM renttable WHERE PLATENUM=?";
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, PlateNumTb1.getText());

            
            Con.close();
        } catch (Exception e) {
        }
    }

    private void DeleteReturnCar() {
        // Implement the method to delete a rent car from the database
        try {
            Con = DriverManager.getConnection(url_db, username_db, password_db);
            String query = "DELETE FROM returntable WHERE PLATENUM=?";
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, PlateNumTb1.getText());
            int row = pst.executeUpdate();
            if (row > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Car Deleted Successfully");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error Deleting Car");
            }
            Con.close();
        } catch (Exception e) {
        }
    }

    private void UpdateCar() {

        try {
            Con = DriverManager.getConnection(url_db, username_db, password_db);
            String Plate = PlateNumTb1.getText();
            String CarStatus = "Available";
            // Update the car status in the database
            String query = "UPDATE carstable SET STATUS=? WHERE PLATENUM=?";
            // Use PreparedStatement to prevent SQL injection
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, CarStatus);
            pst.setString(2, Plate);
            int row = pst.executeUpdate();
            if (row > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Car Has Been Returned Successfully, And Now Available For Rent");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error While Updating Car");
            }
            Con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    

    private void GetCustomers() {
        returnDao.getCustomers(CustNameCb);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseClick;
    private javax.swing.JComboBox<String> CustNameCb;
    private javax.swing.JTextField DelayTb;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField FineTB;
    private javax.swing.JLabel Generatelbl;
    private usu.widget.ButtonGlass LogOutBtn;
    private usu.widget.ButtonGlass ManageCarBtn;
    private javax.swing.JTextField ModelTb;
    private javax.swing.JTextField PlateNumTb1;
    private javax.swing.JButton PrintBtn;
    private usu.widget.ButtonGlass RegisterCustomerBtn;
    private usu.widget.ButtonGlass RentCarBtn;
    private javax.swing.JTable RentTable;
    private javax.swing.JButton ReturnBtn;
    private usu.widget.ButtonGlass ReturnCarBtn;
    private com.toedter.calendar.JDateChooser ReturnDate;
    private javax.swing.JTextField ReturnIdTb;
    private javax.swing.JTable ReturnTable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
